- name: Promote to Domain Controller
  hosts: dc3
  gather_facts: no
  tasks:

    - name: Install Active Directory Domain Services
      win_feature:
        name:
          - AD-Domain-Services
        state: present

    - name: Install DNS Server
      win_feature:
        name:
          - DNS
        state: present

    - name: Install RSAT for Active Directory
      win_feature:
        name:
          - RSAT-AD-AdminCenter
        state: present

    - name: Install RSAT for DNS
      win_feature:
        name:
          - RSAT-DNS-Server
        state: present

    - name: Promote Domain Controller
      win_shell: |
        Install-ADDSDomain -DomainType child -NewDomainName wakanda -ParentDomainName AvangerHQ.at -Credential (Get-Credential "AvangerHQ.at\Administrator") -SafeModeAdministratorPassword (ConvertTo-SecureString "Supergeheim123!" -AsPlainText -Force) -InstallDNS -Confirm:$true
    
    - name: Reboot
      win_reboot:
    
    - name: Set DNS
      ansible.windows.win_shell: |
        Set-DnsClientServerAddress -InterfaceAlias "Wakanda" -ServerAddresses ("10.10.0.1", "192.168.50.1")