- name: Promote to Domain Controller and Join Domain
  hosts: dc2
  gather_facts: no
  tasks:

    - name: Install Active Directory Domain Services
      win_feature:
        name:
          - AD-Domain-Services
        state: present

    - name: Install DNS Server
      win_feature:
        name:
          - DNS
        state: present

    - name: Install RSAT for Active Directory
      win_feature:
        name:
          - RSAT-AD-AdminCenter
        state: present

    - name: Install RSAT for DNS
      win_feature:
        name:
          - RSAT-DNS-Server
        state: present

    - name: Promote server to Domain Controller and Join
      microsoft.ad.domain_controller:
        dns_domain_name: AvangerHQ.at
        domain_admin_user: AvangerHQ\Administrator
        domain_admin_password: Supergeheim123!
        safe_mode_password: Supergeheim123!
        state: domain_controller
        sysvol_path: C:\Windows\SYSVOL
        database_path: C:\Windows\NTDS
        domain_log_path: C:\Windows\NTDS
    
    - name: Reboot
      win_reboot:
        test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'

    - name: Set DNS
      ansible.windows.win_shell: |
        Set-DnsClientServerAddress -InterfaceAlias "LAN" -ServerAddresses ("192.168.50.2", "192.168.50.1")